angular.module('cosmicQuarry',
     [  'ngRoute', 
        'featuredMissions', 
        'allMissions', 
        'missionDetails', 
        'adminPanel', 
        'adminMissionDetails',
        'editMission',
        'addMission',
        'deleteMission',
        'previouslyViewed',
        'accountView',
        'invest',
        'error'
   ]);